services:
  - type: web
    name: analise-vizinhanca
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: "20"
